/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bitwise;

/**
 * _https://www.lintcode.com/problem/1266/
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example Example：
 *
 * Input：s = "abcd"，t = "abcde" Output：'e' 
 * Explanation：'e' is the letter that was added.
 * 
 */
public class FindTheDifference {
    /**
     * @param s: a string
     * @param t: a string
     * @return the letter that was added in t
     */
    public char findTheDifference(String s, String t) {
        char result = 0;
        for(char c : s.toCharArray()){
            result ^= c;
        }
        for(char c : t.toCharArray()){
            result ^= c;
        }

        return result;
    }
}
